/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_cresc_module_update_DownloadTask */

#ifndef _Included_dev_cresc_module_update_DownloadTask
#define _Included_dev_cresc_module_update_DownloadTask
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_cresc_module_update_DownloadTask
 * Method:    hdiffPatch
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_cresc_module_update_DownloadTask_hdiffPatch
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
